### PR TITLE
Dont hang `local x = function` assignments (Take 2)

### LINKED ISSUE #595: stop hanging function assignment at `=`
0.14 introduced a feature where it will hang at the `=` instead of the argument list for many kinds of constructs. There's a particular scenario where this negatively impacts readability:
```lua
exports.createResource = function(
        glitch: (Input) -> Thenable<Value>,
        hasInput: (Input) -> Key,
        config: Config?
): Pleasing<Input, Key, Value>
        config = config or {}
        local pleasing
        pleasing = {
                clear = function(): ()
                        entries[pleasing] = nil
                end,
        }
        return pleasing
end
```

currently gets transformed into this, which in the integration case triggers a cascade of indents
image

### PR DESCRIPTION
**Pull request by JohnnyMorganz**
Extension on #512 

Closes #595

### CODE REVIEW

**Comment by matthargett** [comment]
could we extend this to function call assignments as well?
```lua
     local furryAndFidelity9 = getFurriesAndFidelitiesNames(
             context,
             creamedFurriesAndFidelitiesNames,
             parentType2,
             selectionSet2
     )
```

**Comment by MunifTanjim** [comment]
@matthargett this is the related issue: https://github.com/JohnnyMorganz/StyLua/issues/506

I'm still using `v0.13.x` because of this.

**Comment by JohnnyMorganz** [comment]
PR has been on hold because I need to decide whether to accept the new diff on neovim code in comparison test

**Comment by matthargett** [comment]
FWIW, the Neovim diff looks great to me! ;)

**Pull request merged**
