### PR TITLE
Sort requires

### LINKED ISSUE #364: Sort requires
It would be really neat if stylua could re-order my requires in alphabetical order.

It should be an optional parameter because stylua can't assume that require does not have side effects, but typically it's good practice to avoid them, so generally it's fine 🙂

### PR DESCRIPTION
**Pull request by JohnnyMorganz**
Take 2 on the sort requires system (supersedes #454)
We take a much simpler approach here.

The following assumptions are made when using this codemod:
- All requires are pure and have no side effects: resorting the requires is not an issue
- Only requires at the top level block are to be sorted
- Requires are of the form `local NAME = require(REQUIRE)`, with only a single require per local assignment

Requires sorting works in the following way:
- We group consecutive requires into a "block". If we hit a line which is a non-require or empty, we close the old block and start a new one.
- Requires are sorted only within their block. This allows us to solve the assumption of depending on local variables (if there is a local variable in between requires, it would split them into two separate blocks, so a require will always be after any local variable it uses)
- Blocks remain in-place in the file.
- If any of the block contains an ignore comment (`-- stylua: ignore`), or falls outside of the specified range, then the whole block will be skipped

We also sort services of the form `local NAME = game:GetService(EXPR)` in the same way (treated as a separate group)

Closes #364

### CODE REVIEW

**Comment by Kampfkarren** [comment]
How is capitalization formatted? I have a lot of code that mixes both capital and lowercase initials

**Comment by JohnnyMorganz** [comment]
It is case sensitive. It will sort all uppercase variables before lowercase ones - I've added a test to show this

**Comment by Kampfkarren** [comment]
☹️ i wish it didn't, but i've never been able to get a consistency i like anyway

**Comment by JohnnyMorganz** [comment]
> ☹️ i wish it didn't, but i've never been able to get a consistency i like anyway

We could reasonably add an "ignore case" option here if it better suits

**Pull request merged**
