### PR TITLE
Update readme (collapse_simple_statement)

### PR DESCRIPTION
**Pull request by uga-rosa**

### CODE REVIEW

**Review by JohnnyMorganz — APPROVED** [review]
Thanks!

**Comment by uga-rosa** [comment]
I forgot to update the last, default value section.
Should I PR again? If you want to do it yourself, that's fine.

**Comment by JohnnyMorganz** [comment]
I don't mind. Feel free to open a PR if you want, otherwise I can do it

**Comment by uga-rosa** [comment]
Then I leave it to you.

**Pull request merged**
