### PR TITLE
Fix unstable formatting around comments in type declarations

### LINKED ISSUE #397: Inconsistent formatting when running stylua multiple times
given:
```
--[[comment]]
type Doo
--[[comment]]
<
--[[comment]]
T
--[[comment]]
>
--[[comment]]
= 
--[[comment]]
string
--[[comment]]
```

after stylua becomes:
```
--[[comment]]
type Doo--[[comment]]
<
	--[[comment]]
	T	--[[comment]]

>--[[comment]]
 = --[[comment]]
string
--[[comment]]
```
and running it a second time it becomes:
```
--[[comment]]
type Doo--[[comment]]<
	--[[comment]]
	T --[[comment]]
>--[[comment]] =  --[[comment]]string
--[[comment]]
```
running it more times stays the same.

Expected result: 
* results should be the same everytime stylua is executed

Tested on v0.12.4

### PR DESCRIPTION
**Pull request by JohnnyMorganz**
Fixes #397 (ref: #430)

### CODE REVIEW

**Comment by JohnnyMorganz** [comment]
@matthargett @flakolefluk @ktrz thoughts on the new snapshots?

The newly added snapshots of your tests looks good, but I'm not 100% on the change in the table snapshot (its happening because there is a comment in between the equals token and the table in the declaration)

**Comment by matthargett** [comment]
innnnnteresting. it would be nice if it didn't force the open brace onto the next line with an indent, but I also think the trade-off here is a good one since the affected regression case is a weird/rare one.

**Review by matthargett — APPROVED** [review]

**Review by ktrz — APPROVED** [review]
I think the change in this one snapshot is a good tradeoff for having the stable tool output.

**Comment by flakolefluk** [comment]
snapshots look good to me! i agree with  the previous comments. Let's start with making the output stable.  🎉

**Comment by JohnnyMorganz** [comment]
Turns out the above diff is not related to the PR, but is actually a regression from 0.12.5 -> 0.13.0

**Review by matthargett — APPROVED** [review]

**Pull request merged**
